development:
  adapter: postgresql
  database: goviral_development
  pool: 5
  timeout: 5000
  username: root
  password: password
  host: db
test:
  adapter: postgresql
  database: goviral_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: goviral_production
  pool: 5
  timeout: 5000